# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_v1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(671, 571)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(6, -1, 661, 561))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.edit_YD = QtWidgets.QLineEdit(self.tab_1)
        self.edit_YD.setObjectName("edit_YD")
        self.gridLayout_2.addWidget(self.edit_YD, 9, 1, 1, 1)
        self.edit_XB = QtWidgets.QLineEdit(self.tab_1)
        self.edit_XB.setObjectName("edit_XB")
        self.gridLayout_2.addWidget(self.edit_XB, 4, 1, 1, 1)
        self.edit_XC = QtWidgets.QLineEdit(self.tab_1)
        self.edit_XC.setObjectName("edit_XC")
        self.gridLayout_2.addWidget(self.edit_XC, 6, 1, 1, 1)
        self.edit_XD = QtWidgets.QLineEdit(self.tab_1)
        self.edit_XD.setObjectName("edit_XD")
        self.gridLayout_2.addWidget(self.edit_XD, 8, 1, 1, 1)
        self.edit_YC = QtWidgets.QLineEdit(self.tab_1)
        self.edit_YC.setObjectName("edit_YC")
        self.gridLayout_2.addWidget(self.edit_YC, 7, 1, 1, 1)
        self.edit_YB = QtWidgets.QLineEdit(self.tab_1)
        self.edit_YB.setObjectName("edit_YB")
        self.gridLayout_2.addWidget(self.edit_YB, 5, 1, 1, 1)
        self.edit_XA = QtWidgets.QLineEdit(self.tab_1)
        self.edit_XA.setObjectName("edit_XA")
        self.gridLayout_2.addWidget(self.edit_XA, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_1)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 9, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.edit_YA = QtWidgets.QLineEdit(self.tab_1)
        self.edit_YA.setObjectName("edit_YA")
        self.gridLayout_2.addWidget(self.edit_YA, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.oblicz_btn = QtWidgets.QPushButton(self.tab_1)
        self.oblicz_btn.setMinimumSize(QtCore.QSize(10, 0))
        self.oblicz_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.oblicz_btn.setObjectName("oblicz_btn")
        self.gridLayout_2.addWidget(self.oblicz_btn, 11, 0, 1, 2)
        self.wyczysc_btn = QtWidgets.QPushButton(self.tab_1)
        self.wyczysc_btn.setMinimumSize(QtCore.QSize(10, 0))
        self.wyczysc_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wyczysc_btn.setObjectName("wyczysc_btn")
        self.gridLayout_2.addWidget(self.wyczysc_btn, 12, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 10, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.tab_1)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtWidgets.QLabel(self.tab_1)
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_1)
        self.label_16.setMinimumSize(QtCore.QSize(0, 40))
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setLineWidth(2)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 5, 0, 1, 2)
        self.output_XP = QtWidgets.QLineEdit(self.tab_1)
        self.output_XP.setReadOnly(True)
        self.output_XP.setObjectName("output_XP")
        self.gridLayout_3.addWidget(self.output_XP, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_1)
        self.label_10.setMinimumSize(QtCore.QSize(0, 40))
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setLineWidth(2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 2)
        self.output_AzCD = QtWidgets.QLineEdit(self.tab_1)
        self.output_AzCD.setReadOnly(True)
        self.output_AzCD.setObjectName("output_AzCD")
        self.gridLayout_3.addWidget(self.output_AzCD, 7, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_1)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 7, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_1)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 2)
        self.komentarz_lbl = QtWidgets.QLabel(self.tab_1)
        self.komentarz_lbl.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.komentarz_lbl.setFont(font)
        self.komentarz_lbl.setFrameShape(QtWidgets.QFrame.Box)
        self.komentarz_lbl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.komentarz_lbl.setLineWidth(1)
        self.komentarz_lbl.setText("")
        self.komentarz_lbl.setObjectName("komentarz_lbl")
        self.gridLayout_3.addWidget(self.komentarz_lbl, 2, 0, 1, 2)
        self.output_YP = QtWidgets.QLineEdit(self.tab_1)
        self.output_YP.setReadOnly(True)
        self.output_YP.setObjectName("output_YP")
        self.gridLayout_3.addWidget(self.output_YP, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 8, 0, 1, 2)
        self.output_AzAB = QtWidgets.QLineEdit(self.tab_1)
        self.output_AzAB.setReadOnly(True)
        self.output_AzAB.setObjectName("output_AzAB")
        self.gridLayout_3.addWidget(self.output_AzAB, 6, 1, 1, 1)
        self.zapisz_btn = QtWidgets.QPushButton(self.tab_1)
        self.zapisz_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.zapisz_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zapisz_btn.setObjectName("zapisz_btn")
        self.gridLayout_3.addWidget(self.zapisz_btn, 11, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.tab_1)
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 6, 0, 1, 1)
        self.wyczysc_wyniki_btn = QtWidgets.QPushButton(self.tab_1)
        self.wyczysc_wyniki_btn.setObjectName("wyczysc_wyniki_btn")
        self.gridLayout_3.addWidget(self.wyczysc_wyniki_btn, 12, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rysuj_btn = QtWidgets.QPushButton(self.tab_2)
        self.rysuj_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rysuj_btn.setObjectName("rysuj_btn")
        self.gridLayout_4.addWidget(self.rysuj_btn, 4, 0, 1, 2)
        self.kolor1_btn = QtWidgets.QPushButton(self.tab_2)
        self.kolor1_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kolor1_btn.setObjectName("kolor1_btn")
        self.gridLayout_4.addWidget(self.kolor1_btn, 0, 1, 1, 1)
        self.kolor3_btn = QtWidgets.QPushButton(self.tab_2)
        self.kolor3_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kolor3_btn.setObjectName("kolor3_btn")
        self.gridLayout_4.addWidget(self.kolor3_btn, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.kolor2_btn = QtWidgets.QPushButton(self.tab_2)
        self.kolor2_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kolor2_btn.setObjectName("kolor2_btn")
        self.gridLayout_4.addWidget(self.kolor2_btn, 1, 1, 1, 1)
        self.MplWidget = MplWidget(self.tab_2)
        self.MplWidget.setObjectName("MplWidget")
        self.gridLayout_4.addWidget(self.MplWidget, 5, 0, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_4.addWidget(self.comboBox, 3, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.edit_YD.setText(_translate("Dialog", "17957.41"))
        self.edit_XB.setText(_translate("Dialog", "1144.74"))
        self.edit_XC.setText(_translate("Dialog", "1184.31"))
        self.edit_XD.setText(_translate("Dialog", "1151.14"))
        self.edit_YC.setText(_translate("Dialog", "18004.14"))
        self.edit_YB.setText(_translate("Dialog", "18006.22"))
        self.edit_XA.setText(_translate("Dialog", "1186.00"))
        self.label_5.setText(_translate("Dialog", "YB"))
        self.label_7.setText(_translate("Dialog", "YC"))
        self.label_6.setText(_translate("Dialog", "XC"))
        self.label_9.setText(_translate("Dialog", "YD"))
        self.label_8.setText(_translate("Dialog", "XD"))
        self.label_2.setText(_translate("Dialog", "XA"))
        self.label_3.setText(_translate("Dialog", "YA"))
        self.edit_YA.setText(_translate("Dialog", "17962.69"))
        self.label.setText(_translate("Dialog", "Dane"))
        self.label_4.setText(_translate("Dialog", "XB"))
        self.oblicz_btn.setText(_translate("Dialog", "OBLICZ"))
        self.wyczysc_btn.setText(_translate("Dialog", "WYCZYŚĆ DANE"))
        self.label_12.setText(_translate("Dialog", "YP"))
        self.label_11.setText(_translate("Dialog", "XP"))
        self.label_16.setText(_translate("Dialog", "Azymuty"))
        self.label_10.setText(_translate("Dialog", "Wyniki obliczeń"))
        self.label_18.setText(_translate("Dialog", "AzCD"))
        self.label_19.setText(_translate("Dialog", "Położenie punktu względem odcinka:"))
        self.zapisz_btn.setText(_translate("Dialog", "ZAPISZ"))
        self.label_17.setText(_translate("Dialog", "AzAB"))
        self.wyczysc_wyniki_btn.setText(_translate("Dialog", "WYCZYŚĆ WYNIKI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "Obliczenia"))
        self.rysuj_btn.setText(_translate("Dialog", "Rysuj"))
        self.kolor1_btn.setText(_translate("Dialog", "Wybór koloru"))
        self.kolor3_btn.setText(_translate("Dialog", "Wybór koloru"))
        self.label_20.setText(_translate("Dialog", "Kolor linii C - D"))
        self.kolor2_btn.setText(_translate("Dialog", "Wybór koloru"))
        self.label_21.setText(_translate("Dialog", "Kolor linii A - B"))
        self.label_13.setText(_translate("Dialog", "Kolor punktu P"))
        self.label_14.setText(_translate("Dialog", "Styl punktu P"))
        self.comboBox.setItemText(0, _translate("Dialog", "o"))
        self.comboBox.setItemText(1, _translate("Dialog", "x"))
        self.comboBox.setItemText(2, _translate("Dialog", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Wykres"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

